services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      - test
    ports:
      - 5432:5432
  test:
    image: golang:1.16-alpine
    depends_on:
      - db
    networks:
      - test
    volumes:
      - .:/src
    environment:
      CGO_ENABLED: 0
    working_dir: /src
    command: go test .
    ports:
      - 1234:1234
networks:
  test:
    driver: bridge